### ISSUE TITLE
Invalid OOXML generated when DITA content has footnotes

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/com.elovirta.ooxml#14]
One of our clients encountered a problem with opening a word document obtained from DITA topics which contain footnotes. I'm attaching an archive.
[Archive.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/588073/Archive.zip)
Word tries to recover the document. On Mac, Word crashed completely.

**Comment by LelloFabbi** [comment]
Hi,
I made some improvements in order to avoid Ms Word to crash when opening, but the docm file still have issues.
More in details, the main source changes made are: 
1.	Swap of the footnotes and the <xref> pointing to it.
2.	Removing the "p" tag contained in "fn" tag

While the pdf output file correctly reports the footnote in the page footer with the correct sequential numbering, the docm output file still contain some errors:
-	With use-by-reference "fn" (allowing to reference the same footnote in more than one place), fn number is visualized in the place the "fn" tag is added and there is the “Error! Bookmark not defined” in correspondence of "xref";
-	All the "fn" contents are reported after the table instead of the page footer

The file in attachment contains:
-	Source Ditamap and dita files;
-	PDF and docm outputs with related logs generated
-	Docx file obtained saving the docm after the cross-reference update

[File_for_analysis_Updated.zip](https://github.com/jelovirt/com.elovirta.ooxml/files/684328/File_for_analysis_Updated.zip)

Any comment is welcome
Thank you in advance for your support
