### ISSUE TITLE
Title on the page (header)

### ISSUE THREAD

**Issue by adriankarp** [jelovirt/com.elovirta.ooxml#82]
Hello

Is there a way for the page title to take the map's title value?
Is the word template the only way to modify it?

Thank you!

**Comment by jonathanhanna** [comment]
It already places the map title in the header (and the first line of the document), so I'm a bit confused by what you mean. For example, if I have `<title>Map Title</title>` in my ditamap, I get the following output:
![image](https://user-images.githubusercontent.com/70557962/118894926-060ee780-b8ba-11eb-92ac-c966fee93b01.png)

**Comment by adriankarp** [comment]
It seems that in my case it's placed from the .docx template.

![github](https://user-images.githubusercontent.com/28531641/119321988-df6bfa80-bc85-11eb-9c7b-6be629c127cb.jpg)

**Comment by adriankarp** [comment]
Does anyone have an idea why it might be like this for me?
Thank you

**Comment by jonathanhanna** [comment]
Did you change the Normal.docx file in the resources folder? Where did the "Here goes anything" content come from? Am I correct in assuming the map's title element contains "Vasont and Oxygen Training - Assembling and Publishing Documents"?

**Comment by adriankarp** [comment]
Yes and yes.
I changed from Normal.docx (but even before changing, the default text from the template would be the final output)
And  "Vasont and Oxygen Training - Assembling and Publishing Documents" is my map's title.

If you have any tips, please let me know!
Thank you

**Comment by jonathanhanna** [comment]
It sounds like you modified the header in the Normal.docx file, which is why it is not showing the map title. Try replacing your current Normal.docx file with the default one and run the transformation.

After running the transformation and opening the docx file, you will get a notification asking to update the fields in the document. You must select "Yes" in order for the header to display the map title instead of the default text.

**Comment by adriankarp** [comment]
This solved my problem.
Thank you very much!
